package gradingBuddy.gradingPartner;

public class GenerateHTML {
	
	
	public static String generateHTML(StudentScore studentScore) {
		return "<!-- CSS Code: Place this code in the document's head (between the 'head' tags) -->\r\n"
				+ "		<style>\r\n"
				+ "		table.GeneratedTable {\r\n"
				+ "		  width: 100%;\r\n"
				+ "		  background-color: #ffffff;\r\n"
				+ "		  border-collapse: collapse;\r\n"
				+ "		  border-width: 2px;\r\n"
				+ "		  border-color: #005f95;\r\n"
				+ "		  border-style: solid;\r\n"
				+ "		  color: #000000;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		table.GeneratedTable td, table.GeneratedTable th {\r\n"
				+ "		  border-width: 2px;\r\n"
				+ "		  border-color: #005f95;\r\n"
				+ "		  border-style: solid;\r\n"
				+ "		  padding: 3px;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		table.GeneratedTable thead {\r\n"
				+ "		  background-color: #005f8c;\r\n"
				+ "		}\r\n"
				+ "		</style>\r\n"
				+ "\r\n"
				+ "		<!-- HTML Code: Place this code in the document's body (between the 'body' tags) where the table should appear -->\r\n"
				+ "		<table class=\"GeneratedTable\">\r\n"
				+ "		  <thead>\r\n"
				+ "		    <tr>\r\n"
				+ "		      <th>Question</th>\r\n"
				+ "		      <th>Your Response</th>\r\n"
				+ "		      <th>Status</th>\r\n"
				+ "		    </tr>\r\n"
				+ "		  </thead>\r\n"
				+ "		  <tbody>\r\n"
				+ "		    <tr>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[0].getQuestionNum()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[0].getResponse()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[0].getStatus()+"</td>\r\n"
				+ "		    </tr>\r\n"
				+ "		    <tr>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[1].getQuestionNum()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[1].getResponse()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[1].getStatus()+"</td>\r\n"
				+ "		    </tr>\r\n"
				+ "		    <tr>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[2].getQuestionNum()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[2].getResponse()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[2].getStatus()+"</td>\r\n"
				+ "		    </tr>\r\n"
				+ "		    <tr>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[3].getQuestionNum()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[3].getResponse()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[3].getStatus()+"</td>\r\n"
				+ "		    </tr>\r\n"
				+ "		    <tr>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[4].getQuestionNum()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[4].getResponse()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[4].getStatus()+"</td>\r\n"
				+ "		    </tr>\r\n"
				+ "		    <tr>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[5].getQuestionNum()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[5].getResponse()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[5].getStatus()+"</td>\r\n"
				+ "		    </tr>\r\n"
				+ "		    <tr>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[6].getQuestionNum()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[6].getResponse()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[6].getStatus()+"</td>\r\n"
				+ "		    </tr>\r\n"
				+ "		    <tr>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[7].getQuestionNum()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[7].getResponse()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[7].getStatus()+"</td>\r\n"
				+ "		    </tr>\r\n"
				+ "		    <tr>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[8].getQuestionNum()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[8].getResponse()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[8].getStatus()+"</td>\r\n"
				+ "		    </tr>\r\n"
				+ "		    <tr>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[9].getQuestionNum()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[9].getResponse()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[9].getStatus()+"</td>\r\n"
				+ "		    </tr>\r\n"
				+ "		    <tr>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[10].getQuestionNum()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[10].getResponse()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[10].getStatus()+"</td>\r\n"
				+ "		    </tr>\r\n"
				+ "		    <tr>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[11].getQuestionNum()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[11].getResponse()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[11].getStatus()+"</td>\r\n"
				+ "		    </tr>\r\n"
				+ "		    <tr>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[12].getQuestionNum()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[12].getResponse()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[12].getStatus()+"</td>\r\n"
				+ "		    </tr>\r\n"
				+ "		    <tr>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[13].getQuestionNum()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[13].getResponse()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[13].getStatus()+"</td>\r\n"
				+ "		    </tr>\r\n"
				+ "		    <tr>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[14].getQuestionNum()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[14].getResponse()+"</td>\r\n"
				+ "		      <td>"+studentScore.getScoreLines()[14].getStatus()+"</td>\r\n"
				+ "		    </tr>\r\n"
				+ "		  </tbody>\r\n"
				+ "		</table>\r\n";
	}

}
